// import { css } from "@emotion/css";

export const Colors = {
  Black: "#222222",
  Gray: "#A0A0A0",
  Red: "#FE5d5D",
  White: "#FFFFFF",
  Gray01: "#EAEAEA",
  Gray02: "#CACACA",
  Gray03: "#B3B3B3",
  RawBlack: "#000000",
  RawGray: "#838383",
  PersianRed: "#C42C2C",
  SpringGreen: "#02FF49",
};

export const Images = {
  flower_above: "/assets/images/flower_above.svg",
  flower_bellow: "/assets/images/flower_bellow.svg",
  background_fix: "/assets/images/background_gra.svg",
  urin_logo: "/assets/images/Urin_logo.svg",
  search_icon: "/assets/images/search.svg",
  toggle_icon: "/assets/images/toggle.svg",
  toggle_select: "/assets/images/toggle_select.svg",
  urin_answer: "/assets/images/urin_answer.svg",
  pen_icon: "/assets/images/pen_icon.svg",
  star_qna_group1: "/assets/images/qna_star_fst.svg",
  star_qna_group2: "/assets/images/qna_star_sec.svg",
  cancel_button: "/assets/images/cancel_button.svg",
  question_icon: "/assets/images/question.svg",
  speech_icon: "/assets/images/speech.svg",
  clickheart: "/assets/images/clickheart_shadow.svg",
  smile: "/assets/images/smile.svg",
  smileplus: "/assets/images/smileplus.svg",
  likeheart: "/assets/images/likeheart.svg",

  eiffel_tower: "/assets/images/eiffel_tower.svg",
  calendar_icon: "/assets/images/calendar_icon.svg",
  clock_icon: "/assets/images/clock_icon.svg",
  location_pin_icon: "/assets/images/location_pin_icon.svg",
  dinner_icon: "assets/images/dinner_icon.svg",
  ceremony_icon: "assets/images/ceremony_icon.svg",
  video_icon: "assets/images/video_icon.svg",
  gift_icon: "assets/images/gift_icon.svg",
  clap_icon: "assets/images/clap_icon.svg",
  heart_bubble: "assets/images/heart_bubble.svg",
  heart: "assets/images/heart.svg",
  heart_shadow: "assets/images/heart_shadow.svg",
  location_drawing: "/assets/images/location_drawing.svg",
  google_map_icon: "/assets/images/google_map_icon.svg",
  naver_map_icon: "/assets/images/naver_map_icon.svg",
  kakao_map_icon: "/assets/images/kakao_map_icon.svg",
  copy_addr_icon: "/assets/images/copy_addr_icon.svg",
  envelope_icon: "/assets/images/envelope_icon.svg",
};
