// import { css } from "@emotion/css";

export const Colors = {
  Black: "#222222",
  Gray: "#A0A0A0",
  Red: "#FE5d5D",
  White: "#FFFFFF",
  Gray01: "#EAEAEA",
  Gray02: "#CACACA",
  Gray03: "#B3B3B3",
  RawBlack: "#000000",
  RawGray: "#838383",
  PersianRed: "#C42C2C",
  SpringGreen: "#02FF49",
};

export const Images = {
  flower_above: "/assets/images/flower_above.svg",
  flower_bellow: "/assets/images/flower_bellow.svg",
  background_fix: "/assets/images/background_gra.png",
  urin_logo: "/assets/images/Urin_logo.png",
  search_icon: "/assets/images/search.svg",
  toggle_icon: "/assets/images/toggle.svg",
  toggle_select: "/assets/images/toggle_select.svg",
  urin_answer: "/assets/images/urin_answer.svg",
  pen_icon: "/assets/images/pen_icon.svg",
  cancel_button: "/assets/images/cancel_button.svg",
  question_icon: "/assets/images/question.png",
  speech_icon: "/assets/images/speech.svg",
  // clickheart: "/assets/images/clickheart_shadow.svg",
  clickheart: "/assets/images/clickheart_shadow.png",
  unclickheart: "/assets/images/clickheart.png",
  smile: "/assets/images/smile.svg",
  smileplus: "/assets/images/smileplus.svg",
  likeheart: "/assets/images/likeheart.svg",
  aboutus: "/assets/images/Aboutus-background.svg",
  aboutus_logo: "/assets/images/ico-aboutus-logo.svg",
  aboutus_frendLogo: "/assets/images/aboutus_main_logo.svg",
  aboutus_object1: "/assets/images/ico-aboutus-object1.svg",
  aboutus_minjeong: "/assets/images/minjeong.png",
  aboutus_hellokitty: "/assets/images/hyelee.png",
  aboutus_suhyeon: "/assets/images/suhyeon.png",
  aboutus_sky: "/assets/images/haneul.png",
  line: "/assets/images/line.svg",
  back: "/assets/images/Back.svg",

  star_home_group1: "/assets/images/star_home_group1.svg",
  star_home_group2: "/assets/images/star_home_group2.svg",
  star_qna_group1: "/assets/images/qna_star_fst.svg",
  star_qna_group2: "/assets/images/qna_star_sec.svg",
  star_grtgs_group1: "/assets/images/star_grtgs_group1.svg",
  star_grtgs_group2: "/assets/images/star_grtgs_group2.svg",
  star_details_group1: "/assets/images/star_info_group1.svg",
  star_details_group2: "/assets/images/star_info_group2.svg",
  star_more_group1: "/assets/images/star_more_group1.svg",
  star_more_group2: "/assets/images/star_more_group2.svg",
  object2: "/assets/images/object2.svg",
  object3: "/assets/images/object3.svg",
  object4: "/assets/images/object4.svg",

  ceremony_cake: "/assets/images/ceremony_cake.svg",
  info_date_head: "/assets/images/info_date_head.svg",
  info_time_head: "/assets/images/info_time_head.svg",
  info_place_head: "/assets/images/info_place_head.svg",
  content_chart: "/assets/images/content_chart.svg",
  content_chart2: "/assets/images/content_chart2.svg",
  content_chart3: "/assets/images/content_chart3.svg",
  content_chart4: "/assets/images/content_chart4.svg",
  circle: "/assets/images/circle.svg",
  heart_bubble: "assets/images/heart_bubble.svg",
  heart: "assets/images/heart.svg",
  heart_shadow: "assets/images/heart_shadow.svg",
  location_drawing: "/assets/images/location_drawing.png",
  // googlemap_icon: "/assets/images/googlemap_icon.svg",
  // navermap_icon: "/assets/images/navermap_icon.svg",
  // kakaomap_icon: "/assets/images/kakaomap_icon.svg",
  googlemap_icon: "/assets/images/googlemap_icon.png",
  navermap_icon: "/assets/images/navermap_icon.png",
  kakaomap_icon: "/assets/images/kakaomap_icon.png",
  addr_copy_button: "/assets/images/addr_copy_button.svg",
  team_logo: "/assets/images/team_logo.svg",
  envelope_icon: "/assets/images/envelope_icon.svg",
  cancel_button_white: "/assets/images/cancel_button_white.svg",
  handy_invitation: "/assets/images/handy_invitation.png",
  handy_invitation2: "/assets/images/handy_invitation2.png",
  star_morefunc_group1: "/assets/images/star_morefunc_group1.svg",
  star_morefunc_group2: "/assets/images/star_morefunc_group2.svg",
};
